### ISSUE TITLE
Check format when adding annotation scheme `add_annotation_scheme`

### ISSUE THREAD

**Issue by kidzik** [saliency-ai/saliency-client#2]
First, the description should be a parsable json.
Next, when `type="segmentation"` we expect a list of strings, when `type="form"` we expect a list of dictionaries where each item describes a field in a dictionary:
```json
[
  {
    "name":"Kellgren-Lawrence",
    "type":"select",
    "choices":[
      "0",
      "1",
      "2",
      "3",
      "4"
    ],
    "required":true
  },
  {
    "name":"Joint space",
    "type":"text"
  }
]
```
For now only these two types: `text` and `select`
if `select` then we have a list of choices

**Comment by sotanodroid** [comment]
Not quite get the task.

Now methods receives 3 arguments: name, type, labels.Then it created payload and then makes POST request with this data.

please make it clear which field should I check for containing types?
How many options for the types in total? 4 like test, select, segmentation and form?

Should i somehow transform payload data with different types?

**Comment by kidzik** [comment]
The actual POST request has three fields: `name`, `type`, and `description` (as it can be seen in https://api.saliency.ai/swagger/)

`type` is `"form"` or `"segmentation"`

in the `"form"` task we expect `description` to be the list of form fields of this structure:
```
[
  {
    "name":"Kellgren-Lawrence",
    "type":"select",
    "choices":[
      "0",
      "1",
      "2",
      "3",
      "4"
    ],
    "required":true
  },
  {
    "name":"Joint space",
    "type":"text"
  }
]
```
in the `"segmentation"` mode we just expect a list of strings as a `description` (also JSON compatible)

**Comment by sotanodroid** [comment]
https://github.com/saliency-ai/saliency-client/pull/16
