### ISSUE TITLE
Add functions for listings

### ISSUE THREAD

**Issue by kidzik** [saliency-ai/saliency-client#3]
All listings are quite similar. We need some internal function that covers all listings (eg. `list_objects`), and then individual functions to call it (eg. `list_tasks`)

It'll essentially call a GET on the high level (e.g. `/tasks/`) and return a list of items as a proper pandas data frame so that we can easily display it in python notebooks.

**Comment by sotanodroid** [comment]
https://github.com/saliency-ai/saliency-client/pull/10
