### ISSUE TITLE
Filename conflicts when downloading are causing skipping of the new file

### ISSUE THREAD

**Issue by kidzik** [saliency-ai/saliency-client#6]
Right now if 2 files on the server are called exactly the same and we download both, then the first one will be download and cached and the second one won't be downloaded. 
https://github.com/saliency-ai/saliency-client/blob/1b412a4e80364d2161685ecfaee7dadd7c00a4a8/saliency/saliency.py#L159-L168

This could be solved by adding the unique id to the local path.

**Comment by sotanodroid** [comment]
https://github.com/saliency-ai/saliency-client/pull/11
